name: test-upload
on:
  push:
    branches:
      - main

env:
  IS_CI: true

permissions:
  contents: write

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print file tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: './tests'
          depth: '2'
      - uses: ./
        with:
          files: |
            1so.dmg.zip -> ./tests/一搜_0.1.0_x64.dmg,./tests/1.txt
            1.txt.zip -> ./tests/1.txt
      - run: ls -al
      - name: Print file tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: './'
          depth: '2'
