name: test-upload
on:
  push:
    branches:
      - test

env:
  IS_CI: true

permissions:
  contents: write

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print file tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: './tests'
          depth: '2'
      - name: 打印文件树
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: './tests'
          depth: 2
      - run: cd tests && zip -r 1so.zip 一搜.app
      - run: cd tests && zip 1.zip 1.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./tests/1so.zip
            ./tests/1.zip
          draft: true
